name: weekly_calendar
description: A very simple weekly calendar widget for Flutter.
version: 0.1.0
homepage: https://github.com/mlballack/WeeklyCalendarForFlutter

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.weekly_calendar
        pluginClass: WeeklyCalendarPlugin
      ios:
        pluginClass: WeeklyCalendarPlugin