name: weekly_calendar
description: Effortlessly integrate this straightforward weekly calendar widget into your Flutter app for a seamless user experience. 
version: 0.1.2
homepage: https://github.com/mlballack/WeeklyCalendarForFlutter

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0